function colId(nodeId: string, name: string) {
  return `${nodeId}-${name}`;
}

const C = {
  auth: '#3b82f6',
  core: '#8b5cf6',
  diagram: '#ec4899',
  content: '#f59e0b',
  erd: '#10b981',
  audit: '#f97316',
  ai: '#06b6d4',
  util: '#6b7280',
};

export const purePgNodes = [
  {
    id: 'users',
    type: 'entity',
    position: { x: 0, y: 280 },
    data: {
      id: 'users',
      name: 'users',
      color: C.auth,
      columns: [
        { id: colId('users', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('users', 'email'), name: 'email', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('users', 'password_hash'), name: 'password_hash', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('users', 'display_name'), name: 'display_name', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('users', 'avatar_url'), name: 'avatar_url', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('users', 'is_active'), name: 'is_active', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('users', 'last_login_at'), name: 'last_login_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('users', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('users', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'projects',
    type: 'entity',
    position: { x: 350, y: 80 },
    data: {
      id: 'projects',
      name: 'projects',
      color: C.core,
      columns: [
        { id: colId('projects', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('projects', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('projects', 'description'), name: 'description', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('projects', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('projects', 'is_public'), name: 'is_public', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('projects', 'icon'), name: 'icon', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('projects', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('projects', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'sessions',
    type: 'entity',
    position: { x: 350, y: 240 },
    data: {
      id: 'sessions',
      name: 'sessions',
      color: C.auth,
      columns: [
        { id: colId('sessions', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('sessions', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('sessions', 'token'), name: 'token', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('sessions', 'expires_at'), name: 'expires_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('sessions', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'user_preferences',
    type: 'entity',
    position: { x: 350, y: 400 },
    data: {
      id: 'user_preferences',
      name: 'user_preferences',
      color: C.util,
      columns: [
        { id: colId('user_preferences', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('user_preferences', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('user_preferences', 'preferences'), name: 'preferences', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('user_preferences', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('user_preferences', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'diagrams',
    type: 'entity',
    position: { x: 700, y: 40 },
    data: {
      id: 'diagrams',
      name: 'diagrams',
      color: C.diagram,
      columns: [
        { id: colId('diagrams', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('diagrams', 'project_id'), name: 'project_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('diagrams', 'description'), name: 'description', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'icon'), name: 'icon', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'config'), name: 'config', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'position'), name: 'position', type: 'int4', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'is_current'), name: 'is_current', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('diagrams', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'notes',
    type: 'entity',
    position: { x: 1050, y: 0 },
    data: {
      id: 'notes',
      name: 'notes',
      color: C.content,
      columns: [
        { id: colId('notes', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('notes', 'diagram_id'), name: 'diagram_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('notes', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('notes', 'content'), name: 'content', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('notes', 'style'), name: 'style', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('notes', 'position_x'), name: 'position_x', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('notes', 'position_y'), name: 'position_y', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('notes', 'width'), name: 'width', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('notes', 'height'), name: 'height', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('notes', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('notes', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('notes', 'created_by'), name: 'created_by', type: 'uuid', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'drawings',
    type: 'entity',
    position: { x: 1050, y: 120 },
    data: {
      id: 'drawings',
      name: 'drawings',
      color: C.content,
      columns: [
        { id: colId('drawings', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('drawings', 'diagram_id'), name: 'diagram_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'label'), name: 'label', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'icon'), name: 'icon', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'style'), name: 'style', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'position_x'), name: 'position_x', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'position_y'), name: 'position_y', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'width'), name: 'width', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'height'), name: 'height', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('drawings', 'created_by'), name: 'created_by', type: 'uuid', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'flowcharts',
    type: 'entity',
    position: { x: 1050, y: 240 },
    data: {
      id: 'flowcharts',
      name: 'flowcharts',
      color: C.content,
      columns: [
        { id: colId('flowcharts', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('flowcharts', 'diagram_id'), name: 'diagram_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'parent_id'), name: 'parent_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'label'), name: 'label', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'style'), name: 'style', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'shape'), name: 'shape', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'data'), name: 'data', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'position_x'), name: 'position_x', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'position_y'), name: 'position_y', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'width'), name: 'width', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'height'), name: 'height', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('flowcharts', 'created_by'), name: 'created_by', type: 'uuid', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'entities',
    type: 'entity',
    position: { x: 1050, y: 360 },
    data: {
      id: 'entities',
      name: 'entities',
      color: C.erd,
      columns: [
        { id: colId('entities', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('entities', 'diagram_id'), name: 'diagram_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('entities', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('entities', 'schema_name'), name: 'schema_name', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('entities', 'color'), name: 'color', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('entities', 'position_x'), name: 'position_x', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('entities', 'position_y'), name: 'position_y', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('entities', 'width'), name: 'width', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('entities', 'height'), name: 'height', type: 'float8', is_pk: false, is_nullable: true },
        { id: colId('entities', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('entities', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'relationships',
    type: 'entity',
    position: { x: 1050, y: 520 },
    data: {
      id: 'relationships',
      name: 'relationships',
      color: C.erd,
      columns: [
        { id: colId('relationships', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('relationships', 'diagram_id'), name: 'diagram_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'source_entity_id'), name: 'source_entity_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'target_entity_id'), name: 'target_entity_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'source_column_id'), name: 'source_column_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'target_column_id'), name: 'target_column_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'label'), name: 'label', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'style'), name: 'style', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('relationships', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'columns',
    type: 'entity',
    position: { x: 1400, y: 320 },
    data: {
      id: 'columns',
      name: 'columns',
      color: C.erd,
      columns: [
        { id: colId('columns', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('columns', 'entity_id'), name: 'entity_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('columns', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('columns', 'type'), name: 'type', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('columns', 'length'), name: 'length', type: 'int4', is_pk: false, is_nullable: true },
        { id: colId('columns', 'is_nullable'), name: 'is_nullable', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('columns', 'is_unique'), name: 'is_unique', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('columns', 'is_primary_key'), name: 'is_primary_key', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('columns', 'is_foreign_key'), name: 'is_foreign_key', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('columns', 'references_table'), name: 'references_table', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'references_column'), name: 'references_column', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'on_delete'), name: 'on_delete', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'default_value'), name: 'default_value', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'check_expression'), name: 'check_expression', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'comment'), name: 'comment', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('columns', 'position'), name: 'position', type: 'int4', is_pk: false, is_nullable: true },
        { id: colId('columns', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('columns', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'entity_changes',
    type: 'entity',
    position: { x: 1400, y: 500 },
    data: {
      id: 'entity_changes',
      name: 'entity_changes',
      color: C.audit,
      columns: [
        { id: colId('entity_changes', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('entity_changes', 'entity_id'), name: 'entity_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'action'), name: 'action', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'change_type'), name: 'change_type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'old_values'), name: 'old_values', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'new_values'), name: 'new_values', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'changed_by'), name: 'changed_by', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('entity_changes', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'backups',
    type: 'entity',
    position: { x: 700, y: 160 },
    data: {
      id: 'backups',
      name: 'backups',
      color: C.util,
      columns: [
        { id: colId('backups', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('backups', 'project_id'), name: 'project_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('backups', 'backup_type'), name: 'backup_type', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('backups', 'file_path'), name: 'file_path', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('backups', 'size_bytes'), name: 'size_bytes', type: 'int8', is_pk: false, is_nullable: true },
        { id: colId('backups', 'metadata'), name: 'metadata', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('backups', 'created_by'), name: 'created_by', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('backups', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'ai_providers',
    type: 'entity',
    position: { x: 0, y: 720 },
    data: {
      id: 'ai_providers',
      name: 'ai_providers',
      color: C.ai,
      columns: [
        { id: colId('ai_providers', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('ai_providers', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('ai_providers', 'base_url'), name: 'base_url', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_providers', 'api_key_env_var'), name: 'api_key_env_var', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_providers', 'is_enabled'), name: 'is_enabled', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('ai_providers', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('ai_providers', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'ai_models',
    type: 'entity',
    position: { x: 350, y: 640 },
    data: {
      id: 'ai_models',
      name: 'ai_models',
      color: C.ai,
      columns: [
        { id: colId('ai_models', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('ai_models', 'provider_id'), name: 'provider_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_models', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('ai_models', 'display_name'), name: 'display_name', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_models', 'max_tokens'), name: 'max_tokens', type: 'int4', is_pk: false, is_nullable: true },
        { id: colId('ai_models', 'is_enabled'), name: 'is_enabled', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('ai_models', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('ai_models', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'user_ai_configs',
    type: 'entity',
    position: { x: 700, y: 600 },
    data: {
      id: 'user_ai_configs',
      name: 'user_ai_configs',
      color: C.ai,
      columns: [
        { id: colId('user_ai_configs', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('user_ai_configs', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'provider_id'), name: 'provider_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'model_id'), name: 'model_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'api_key'), name: 'api_key', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'is_active'), name: 'is_active', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'config'), name: 'config', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('user_ai_configs', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'ai_chat_sessions',
    type: 'entity',
    position: { x: 700, y: 760 },
    data: {
      id: 'ai_chat_sessions',
      name: 'ai_chat_sessions',
      color: C.ai,
      columns: [
        { id: colId('ai_chat_sessions', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('ai_chat_sessions', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'title'), name: 'title', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'provider_id'), name: 'provider_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'model_id'), name: 'model_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'system_prompt_id'), name: 'system_prompt_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'config'), name: 'config', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'is_archived'), name: 'is_archived', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_sessions', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'user_ai_rules',
    type: 'entity',
    position: { x: 350, y: 840 },
    data: {
      id: 'user_ai_rules',
      name: 'user_ai_rules',
      color: C.ai,
      columns: [
        { id: colId('user_ai_rules', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('user_ai_rules', 'user_id'), name: 'user_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('user_ai_rules', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('user_ai_rules', 'content'), name: 'content', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('user_ai_rules', 'is_active'), name: 'is_active', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('user_ai_rules', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('user_ai_rules', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'ai_chat_messages',
    type: 'entity',
    position: { x: 1050, y: 720 },
    data: {
      id: 'ai_chat_messages',
      name: 'ai_chat_messages',
      color: C.ai,
      columns: [
        { id: colId('ai_chat_messages', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('ai_chat_messages', 'session_id'), name: 'session_id', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_messages', 'role'), name: 'role', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_messages', 'content'), name: 'content', type: 'text', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_messages', 'metadata'), name: 'metadata', type: 'jsonb', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_messages', 'token_count'), name: 'token_count', type: 'int4', is_pk: false, is_nullable: true },
        { id: colId('ai_chat_messages', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },
  {
    id: 'ai_system_prompts',
    type: 'entity',
    position: { x: 1050, y: 840 },
    data: {
      id: 'ai_system_prompts',
      name: 'ai_system_prompts',
      color: C.ai,
      columns: [
        { id: colId('ai_system_prompts', 'id'), name: 'id', type: 'uuid', is_pk: true, is_nullable: false },
        { id: colId('ai_system_prompts', 'name'), name: 'name', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('ai_system_prompts', 'content'), name: 'content', type: 'text', is_pk: false, is_nullable: false },
        { id: colId('ai_system_prompts', 'is_default'), name: 'is_default', type: 'boolean', is_pk: false, is_nullable: true },
        { id: colId('ai_system_prompts', 'created_by'), name: 'created_by', type: 'uuid', is_pk: false, is_nullable: true },
        { id: colId('ai_system_prompts', 'created_at'), name: 'created_at', type: 'timestamptz', is_pk: false, is_nullable: true },
        { id: colId('ai_system_prompts', 'updated_at'), name: 'updated_at', type: 'timestamptz', is_pk: false, is_nullable: true },
      ],
    },
  },

];

const ec = (color: string) => ({ stroke: color, strokeWidth: 2, opacity: 0.5 });

export const purePgEdges = [
  { id: 'e-users-projects', source: 'users', target: 'projects', style: ec(C.auth) },
  { id: 'e-users-sessions', source: 'users', target: 'sessions', style: ec(C.auth) },
  { id: 'e-users-user_preferences', source: 'users', target: 'user_preferences', style: ec(C.auth) },
  { id: 'e-users-user_ai_configs', source: 'users', target: 'user_ai_configs', style: ec(C.auth) },
  { id: 'e-projects-diagrams', source: 'projects', target: 'diagrams', style: ec(C.core) },
  { id: 'e-diagrams-notes', source: 'diagrams', target: 'notes', style: ec(C.diagram) },
  { id: 'e-diagrams-drawings', source: 'diagrams', target: 'drawings', style: ec(C.diagram) },
  { id: 'e-diagrams-flowcharts', source: 'diagrams', target: 'flowcharts', style: ec(C.diagram) },
  { id: 'e-diagrams-entities', source: 'diagrams', target: 'entities', style: ec(C.diagram) },
  { id: 'e-diagrams-relationships', source: 'diagrams', target: 'relationships', style: ec(C.diagram) },
  { id: 'e-entities-columns', source: 'entities', target: 'columns', style: ec(C.erd) },
  { id: 'e-entities-entity_changes', source: 'entities', target: 'entity_changes', style: ec(C.erd) },
  { id: 'e-backups-projects', source: 'backups', target: 'projects', style: ec(C.util) },
  { id: 'e-ai_providers-ai_models', source: 'ai_providers', target: 'ai_models', style: ec(C.ai) },
  { id: 'e-ai_providers-user_ai_rules', source: 'ai_providers', target: 'user_ai_rules', style: ec(C.ai) },
  { id: 'e-ai_models-user_ai_configs', source: 'ai_models', target: 'user_ai_configs', style: ec(C.ai) },
  { id: 'e-ai_models-ai_chat_sessions', source: 'ai_models', target: 'ai_chat_sessions', style: ec(C.ai) },
  { id: 'e-ai_providers-user_ai_configs', source: 'ai_providers', target: 'user_ai_configs', style: ec(C.ai) },
  { id: 'e-ai_providers-ai_chat_sessions', source: 'ai_providers', target: 'ai_chat_sessions', style: ec(C.ai) },
  { id: 'e-ai_chat_sessions-ai_system_prompts', source: 'ai_chat_sessions', target: 'ai_system_prompts', style: ec(C.ai) },
  { id: 'e-ai_chat_messages-ai_chat_sessions', source: 'ai_chat_messages', target: 'ai_chat_sessions', style: ec(C.ai) },

];
